config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'schedules#index'
  get 'schedules/search'
  get 'airlines/index'
  get 'airplanes/index'
  resources :airplanes, only:[:show]
end

app/models/airline.rb
class Airline < ApplicationRecord
  
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departure.rb
class Departure < ApplicationRecord
  has_many :schedules
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :departure
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  with_options presence: true do
    validates :nickname
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :first_name
    validates :last_name
  end
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  def index
  end

end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  def index
    @airplanes = Airplane.all
  end
  
  def show
    @airplane = Airplane.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :search_schedule, only: [:index, :search]

  def index
    @schedules = Schedule.all #全スケジュールの情報を取得
    set_schedule_column
    set_departure_column
  end

  def search
    @results = @p.result.includes(:departure)
    unless user_signed_in?
      redirect_to new_user_session_path
    end  
  end
  private

  def search_schedule
    @p = Schedule.ransack(params[:q]) #検索オブジェクトを生成
  end

  def set_schedule_column
    @schedule_country = Schedule.select("country").distinct #重複なくcountryカラムのデータを取り出す
    @schedule_day = Schedule.select("day").distinct
    @schedule_model = Schedule.select("model").distinct
  end

  def set_departure_column
    @departure_departure = Departure.select("departure").distinct
  end


end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/airlines/index.html.erb
<%= render "shared/second-header"%>

<main class="main">
  <h1 class="index-top">航空会社一覧 </h1>
  <div class="inner">
    <div class="card__wrapper">
          <div class="card">
            <div class="airline-image"><a href ="https://cargo.koreanair.com/"><img src="/assets/korean-air.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://cargo.koreanair.com/">大韓航空(KE)</a></h2>
            </div>
          </div>

           <div class="card">
           <div class="airline-image"><a href ="https://www.anacargo.jp/ja/"><img src="/assets/ANA.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.anacargo.jp/ja/">全日本空輸(NH)</a></h2>
            </div>
          </div>

          <div class="card">
            <div class="airline-image"><a href ="https://www.jal.co.jp/jalcargo/"><img src="/assets/JAL.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.jal.co.jp/jalcargo/">日本航空(JL)</a></h2>
            </div>
          </div>

          <div class="card">
            <div class="airline-image"><a href ="https://www.asianacargo.com/home.do"><img src="/assets/ASIANA.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.asianacargo.com/home.do">アシアナ航空(OZ)</a></h2>
            </div>
          </div>

          <div class="card">
           <div class="airline-image"><a href ="https://www.nca.aero/main.html/"><img src="/assets/NCA.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.nca.aero/main.html/">日本貨物航空(KZ)</a></h2>
            </div>
          </div>

          <div class="card">
           <div class="airline-image"><a href ="https://www.aircanada.com/cargo/en/"><img src="/assets/AC.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.aircanada.com/cargo/en/">エアーカナダ(AC)</a></h2>
            </div>
          </div>

           <div class="card">
           <div class="airline-image"><a href ="https://www.silkwaywest.com/home/"><img src="/assets/7L.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.silkwaywest.com/home/">シルクウェイ ウェスト航空(7L)</a></h2>
            </div>
          </div>

           <div class="card">
           <div class="airline-image"><a href ="https://aircargo.ups.com/"><img src="/assets/UPS.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://aircargo.ups.com/">UPS(5X)</a></h2>
            </div>
          </div>

           <div class="card">
           <div class="airline-image"><a href ="https://www.brcargo.com/ec_web/Default.aspx"><img src="/assets/BR.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.brcargo.com/ec_web/Default.aspx">エバー航空(BR)</a></h2>
            </div>
          </div>

           <div class="card">
           <div class="airline-image"><a href ="https://cargo.china-airlines.com/ccnetv2/content/home/index.aspx"><img src="/assets/CI.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://cargo.china-airlines.com/ccnetv2/content/home/index.aspx">チャイナエアライン(CI)</a></h2>
            </div>
          </div>

           <div class="card">
           <div class="airline-image"><a href ="https://www.cathaypacificcargo.com/"><img src="/assets/CX.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.cathaypacificcargo.com/">キャセイパシフィック(CX)</a></h2>
            </div>
          </div>


           <div class="card">
           <div class="airline-image"><a href ="https://www.skycargo.com/"><img src="/assets/EK.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.skycargo.com/">エミレーツ航空(EK)</a></h2>
            </div>
          </div>



           <div class="card">
           <div class="airline-image"><a href ="https://www.etihadcargo.com/en-ae"><img src="/assets/EY.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.etihadcargo.com/en-ae">エティハド航空(EY)</a></h2>
            </div>
          </div>


           <div class="card">
           <div class="airline-image"><a href ="https://lufthansa-cargo.com/home"><img src="/assets/LH.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://lufthansa-cargo.com/home">ルフトハンザ ドイツ航空(LH)</a></h2>
            </div>
          </div>


           <div class="card">
           <div class="airline-image"><a href ="https://www.swissworldcargo.com/en/home"><img src="/assets/LX.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.swissworldcargo.com/en/home">スイスインターナショナルエアラインズ(LX)</a></h2>
            </div>
          </div>



          <div class="card">
           <div class="airline-image"><a href ="https://www.polaraircargo.com/"><img src="/assets/PO.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.polaraircargo.com/">ポーラ・エアカーゴ(PO)</a></h2>
            </div>
          </div>

          <div class="card">
           <div class="airline-image"><a href ="https://www.airbridgecargo.com/en/tracking/"><img src="/assets/RU.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="https://www.airbridgecargo.com/en/tracking/">エアブリッジカーゴ(RU)</a></h2>
            </div>
          </div>

                     <div class="card">
           <div class="airline-image"><a href ="http://www.siacargo.com/"><img src="/assets/SQ.png" class="card__img"></a></div>
            <div class="card__body">
             <h2 class="card__title"> <a href ="http://www.siacargo.com/">シンガポール航空(SQ)</a></h2>
            </div>
          </div>


   </div>
  </div>
</main>

  <%= link_to 'トップページへ戻る', root_path %>

    <!-- /.main -->

app/views/airplanes/index.html.erb
<%= render "shared/header" %>


<h1 class="title">航空機材一覧</h1>

<div class="table-name">
  <p class="table-title">機材名</p>
  <p class="table-title">機材名(フルネーム)</p>
</div>

<% @airplanes.each do |airplane| %>
  <table>
    <tr>
      <td class=""><%= link_to"#{ airplane.equipment}",airplane_path(airplane.id) %></td>
      <td><%= airplane.eq_name %></td>
    </tr> 
  </table> 
<% end %>

  <%= link_to 'トップページへ戻る', root_path %>

<%= render "shared/footer" %>

app/views/airplanes/show.html.erb
<%= render "shared/header" %>

<div class="airplane-show">
  <div class="airplane-show-box">
    <table class="airplane-details-table">
      <tbody>
        <tr>
          <th class="airplane-details">機材名(3レター)</th>
          <td class="airplane-value"><%= @airplane.equipment %></td>
        </tr>
        <tr>
          <th class="airplane-details">機材名(フルネーム)</th>
          <td class="airplane-value"><%= @airplane.eq_name%></td>
        </tr> 
        <tr>
          <th class="airplane-details">説明</th>
          <td class="airplane-value"><%= @airplane.explain %></td>
        </tr>
        <tr>
          <th class="airplane-details"></th>
          <td class="airplane-value"> <%= image_tag @airplane.image, class: 'airplane-image' %></td>
        </tr>
      </tbody>
    </table> 
  </div>
  <div class='airplane-footer'>
    <%= button_to "トップページに戻る", root_path, { method: :get, class: "airplane-footer-title"} %> 
    <%= button_to '機材一覧ページへ戻る', airplanes_index_path, { method: :get, class: "airplane-footer-title"} %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
     <%= breadcrumbs separator: " &rsaquo; " %>   
    <%= yield %>
  </body>
</html>

app/views/schedules/index.html.erb
<%= render "shared/header" %>
 <% breadcrumb :root %> <%#パンクズ機能追加 %>

<div class="index-page">
  <div class="all-images">
      <div class="b"><img class="flight-image" id="images" src="assets/flight1.png"></div>
  </div>

  <%= search_form_for @p, url: schedules_search_path do |f| %>
    <div class="all-search-form">
      <p class='body-title'>FRIGHT SEARCH</p>
      <div class = "search-form">
        <div class="departure-form">
          <%= f.label :departure_departure_eq, '出発地' %>
          <%= f.collection_select :departure_departure_eq, @departure_departure, :departure, :departure,  include_blank: '指定なし'%>
          <br>
        <p class="form-explain"> 出発地の選択はこちらから </p>
        </div> 
        <div class="arrive-form">
          <%= f.label :country_eq, '到着地' %>
          <%= f.collection_select :country_eq, @schedule_country, :country, :country,  include_blank: '指定なし' %>
          <br>
        <p class="form-explain">到着地の選択はこちらから</p>
        </div>   
      </div>  
      <div class="day-form">
        <%= f.label :day_eq, '曜日' %>
        <%= f.collection_select :day_eq, @schedule_day, :day, :day,  include_blank: '指定なし' %>
        <br> 
        <p class="form-explain">曜日の指定はこちらから</p>
      </div>  
      <div class="model-form">
        <%= f.label :model, '旅客便 or 貨物便:' %>
          <%= f.radio_button :model_eq, '旅客便' %>
          旅客便
          <%= f.radio_button :model_eq, '貨物便' %>
          貨物便
          <br>
        <p class="form-explain">旅客便・貨物便の指定はこちらから </p>
      </div>
      <div class="search-btn">
        <%= f.submit 'SEARCH' %>
        <br>
      </div> 
    </div> 
  <% end %>
</div>
<%= render "shared/footer-link" %>
<%= render "shared/footer" %>

app/views/schedules/search.html.erb
<%= render "shared/header" %>
<% breadcrumb :search_schedule %>

<div class="all-search-form">
  <h1> 検索結果</h1>
  <%# 検索結果の個数で条件分岐 %>
  <% if @results.length !=0 %>
    <% @results.each do |result| %>
    <div class="flight-schedules">
          <td>
          <br>
          <li class="results-top">
            <p class="airline-name"><%= "便名：#{result.airline}#{result.fltnum}" %></p>
            <p class="day"><%= "曜日 : #{result.day}曜発" %></p>
          </li> 

          <li class="results-middle">
            <span class="airport"><%= "出発空港：#{result.departure.departure}  ⇨ 到着国 : #{result.country}" %></span>
          </li>

          <li class="results-bottom">
           <span class="time"> <%= "出発時刻:#{result.dptime.strftime('%H:%M')} ⇨ 到着時刻：#{result.artime.strftime('%H:%M')}" %></span>
          </li>
    </div> 
    <% end %>
  <% else %>
    該当する商品はありません
  <% end %>
  <br>
  <%= link_to 'トップページへ戻る', root_path %>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer-link.html.erb
<div class='ad-footer-contents'>
  <h2>  <%= button_to "航空会社一覧", airlines_index_path, { method: :get, class: "ad-footer-title"} %> </h2>
</div>
<div class='ad-footer-contents'>
  <h2><%= button_to "フライト機材一覧", airplanes_index_path, { method: :get, class: "ad-footer-title"} %></h2>
</div>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='flight-search-details'>
      <h2 class='footer-content-head'>FRIGHT-SEARCHについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FRIGHT-SEARCH利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='flight-search-details'>
      <h2 class='footer-content-head'>FRIGHT-SEARCHを見る</h2>
      <ul>
        <li><%= link_to '航空会社一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'フライトスケジュール一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='flight-search-details'>
      <h2 class='footer-content-head'>FRIGHT-SEARCHについて</h2>
      <ul>
        <li><%= link_to 'FRIGHT-SEARCHガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FRIGHT-SEARCHロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <p>© FRIGHT SEARCH</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='nav'>
       <%= link_to image_tag("flight-search-logo.png", class:"flight-search-icon"), "/" %>
    <ul class='lists'>
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, root_path, class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト',  destroy_user_session_path, method: :delete, class: "logout" %></li> 
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("flight-search-logo.png", class:"second-logo") %>
</header>